name: Cache GitHub README Stats and Contribution Animation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  update-assets:
    runs-on: ubuntu-latest
    name: Update, Generate, and Commit Assets
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create assets directory
        run: mkdir -p assets

      # --- GitHub README Stats ---
      - name: Download the stats file
        run: curl 'https://g-r-s.vercel.app/api?username=Ju1-js&include_all_commits=true&locale=en&show=prs_merged&show_icons=true&theme=transparent&border_radius=10&border_color=00000000' -o assets/stats.svg

      - name: Download the top languages file
        run: curl 'https://g-r-s.vercel.app/api/top-langs?username=Ju1-js&size_weight=0.4&count_weight=0.6&langs_count=20&show_icons=true&theme=transparent&layout=compact&border_radius=10&border_color=00000000' -o assets/top-langs.svg
        
      - name: Download the streak stats file
        run: curl 'https://grss.vercel.app?user=Ju1-js&theme=transparent&mode=weekly&border=00000000' -o assets/streak.svg

      # --- GitHub Pinned Repos ---
      - name: Download the 25th-hour-dynamic pin
        run: curl 'https://g-r-s.vercel.app/api/pin/?username=Ju1-js&repo=25th-hour-dynamic&show_icons=true&theme=transparent&border_radius=10&border_color=00000000' -o assets/25th-hour-dynamic.svg
        
      - name: Download the Ju1-js.github.io pin
        run: curl 'https://g-r-s.vercel.app/api/pin/?username=Ju1-js&repo=Ju1-js.github.io&show_icons=true&theme=transparent&border_radius=10&border_color=00000000' -o assets/Ju1-js.github.io.svg

      - name: Download the Vercel-Troll-Site pin
        run: curl 'https://g-r-s.vercel.app/api/pin/?username=Ju1-js&repo=Vercel-Troll-Site&show_icons=true&theme=transparent&border_radius=10&border_color=00000000' -o assets/Vercel-Troll-Site.svg

      - name: Download the discord-webhook pin
        run: curl 'https://g-r-s.vercel.app/api/pin/?username=Ju1-js&repo=discord-webhook&show_icons=true&theme=transparent&border_radius=10&border_color=00000000' -o assets/discord-webhook.svg

      # --- Contribution Animation (snk) ---
      - name: Generate contribution SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      # --- Commit Changes (Combined) ---
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(assets): update GRS and snk files"
          commit_user_name: Ju1-js
          commit_user_email: 40339350+Ju1-js@users.noreply.github.com
          file_pattern: assets/*.svg
